### ISSUE TITLE
[ISSUE] 메뉴 데이터 관련 이슈 의논 필요

### ISSUE THREAD

**Issue by thguss** [Health-Food-Me/Health-Food-Me-Server#90]
## What is this issue? 🚀
샐러디와 같은 프렌차이저는 메뉴가 통일되서 Menu.from에 참조되는 값(식당 지점)이 유일하지 않는 경우도 발생하게 됩니다. 
제가 아는 바로는 이제까지 Menu.from 필드를 사용한 적이 없는 것으로 아는데, Menu 스키마에서 from 필드를 제거하고 식당에서 메뉴를 참조하는 구조로 변경하면 어떨꺼요?

summary: 다중 값 이슈로 Menu 스키마에서 from 필드를 삭제할 것을 제안함.

## Progress 🏃‍♀️
- [ ]

**Comment by thguss** [comment]
@l2hyunwoo 식당과 메뉴가 서로 필드를 참조하고 있는 구조에서 다중 값 이슈까지 발생해서 이와 같이 생각하는데 어떠신가유

**Comment by l2hyunwoo** [comment]
맞아 이 부분 체인점 고려안하고 설계안한거여서 레스토랑이 메뉴 id를 들고가는게 맞아

**Comment by thguss** [comment]
@l2hyunwoo 오키 그럼 메뉴 쪽에 레스토랑 id 필드 제거 하도록 하겟슴다
